name: Called-WF

on:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string

jobs:
    deploy-in-dev:
        name: Deploy to ${ { inputs.target-env } }
        runs-on: ubuntu-latest
        if: inputs.target-env == 'dev'
        steps:
            - name: Deploy to dev
              run: echo "dev"
    deploy-in-test:
        name: Deploy to ${ { inputs.target-env } }
        runs-on: ubuntu-latest
        if: inputs.target-env == 'test'
        steps:
            - name: Deploy to test
              run: echo "test"