name: Calling-WF
on:
    workflow_dispatch:
        inputs:
            Environment:
                type: choice
                description: Environment to Deploy
                options: 
                    - dev
                    - test

    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Some Job
              run: echo "Hello! World"
    helm-packge:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Helm Package
              run: echo "Helm Package"
    reusable-wf:
        needs: helm-packge
        uses: ./.github/workflows/called-wf.yaml
        with:
            target-env: ${{ inputs.Environment }}