name: PR-Merge-to-main
on:
    workflow_dispatch:
    pull_request:
        types:
            - opened
            - closed
        branches:
            - main

run-name: "This workflow is triggered by @${{ github.actor }} on the event: ${{ github.event_name }}"

jobs:
    PR-Merge-open:
      if: ${{ github.event.pull_request.merged == false && github.event_name != 'workflow_dispatch' }}
      runs-on: ubuntu-latest
      steps:
        - name: build
          run: | 
            echo "Gradle Build @" $(date)
            echo ${{ github.ref }}

    PR-Merge-closed:
       if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
       runs-on: ubuntu-latest
       steps:
        - name: build
          run: | 
            echo "Gradle Build @" $(date)
            echo ${{ github.ref }}
    
    Docker-Build:
      runs-on: ubuntu-latest
      if: ${{ github.event.pull_request.merged == true && github.event_name == 'workflow_dispatch' }}
      needs: PR-Merge-closed
      steps:
        - name: docker-build
          run: echo "Docker Build @" $(date)
      
    Helm-Package:
      runs-on: ubuntu-latest
      if: ${{ github.event.pull_request.merged == true && github.event_name == 'workflow_dispatch' }}
      needs: Docker-Build
      steps:
        - name: helm package
          run: echo "Helm Package @" $(date)

    Deploy-to-dev:
      runs-on: ubuntu-latest
      if: ${{ github.event.pull_request.merged == true && github.event_name == 'workflow_dispatch' }}
      environment: dev
      needs: Helm-Package
      steps:
        - name: Dev Deployment
          run: echo "Deployed to Dev @" $(date)
    
    Deploy-to-test:
      runs-on: ubuntu-latest
      if: ${{ github.event.pull_request.merged == true && github.event_name == 'workflow_dispatch' }}
      environment: test
      needs: Helm-Package
      steps:
        - name: Test Deploymnet
          run: echo "Deployed to Test @" $(date)
    
    Deploy-to-bce:
      runs-on: ubuntu-latest
      if: ${{  github.event.pull_request.merged == true && github.event_name == 'workflow_dispatch' }}
      environment: bce
      needs: Helm-Package
      steps:
        - name: BCE Deploymnet
          run: echo "Deployed to BCE @" $(date)