name: PR-Merge-to-main
on:
    pull_request:
        types:
            - opened
            - closed
        branches:
            - main

run-name: "This workflow is triggered by @${{ github.actor }} on the event: ${{ github.event_name }}"

jobs:
    PR-Merge-open:
      if: ${{ github.event.pull_request.merged == false }}
      runs-on: ubuntu-latest
      steps:
        - name: build
          run: | 
            echo "Gradle Build @" $(date)
            echo ${{ github.ref }}

    PR-Merge-closed:
       if: ${{ github.event.pull_request.merged == true }}
       runs-on: ubuntu-latest
       steps:
        - name: build
          run: | 
            echo "Gradle Build @" $(date)
            echo ${{ github.ref }}
    
    Docker-Build:
      runs-on: ubuntu-latest
      if: ${{ github.event.pull_request.merged == true }}
      needs: PR-Merge-closed
      steps:
        - name: docker-build
          run: echo "Docker Build @" $(date)
      
    Helm-Package:
      runs-on: ubuntu-latest
      if: ${{ github.event.pull_request.merged == true }}
      needs: Docker-Build
      steps:
        - name: helm package
          run: echo "Helm Package @" $(date)