name: Release
on:
    workflow_dispatch:

run-name: "This workflow is triggered by @ ${{ github.actor }} on the event: ${{ github.event_name }}"

jobs:
    Gradle-Build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Gradle build on $(date)"

    Run-Scans-Tests:
        runs-on: ubuntu-latest
        needs: Gradle-Build
        steps:
            - name: Running Scans and Unit Test
              run: echo "Scanned at $(date)"
    
    Docker-Build:
        runs-on: ubuntu-latest
        needs: Run-Scans-Tests
        steps:
            - name: Docker build
              run: echo "Docker build on $(date)"

    Helm-Package:
        runs-on: ubuntu-latest
        needs: Docker-Build
        steps:
            - name: Helm Package
              run: echo "Helm Package on $(date)"
    
    Deploy-to-cert:
        runs-on: ubuntu-latest
        needs: Helm-Package
        environment: cert
        steps:
            - name: Deploy to cert
              run: echo "Deployed on cert on $(date)"

    Deploy-to-pre-prod:
        runs-on: ubuntu-latest
        needs: Deploy-to-cert
        environment: pre-prod
        steps:
            - name: Deploy to pre-prod
              run: echo "Deployed on pre-prod on $(date)"

    Deploy-to-prod:
        runs-on: ubuntu-latest
        needs: Deploy-to-pre-prod
        environment: prod
        steps:
            - name: Deploy to prod
              run: echo "Deployed on prod on $(date)"